import { Baloo_Bhai_2 } from 'next/font/google'
import './globals.css'

const baloo = Baloo_Bhai_2({
   subsets: ['latin'],
   weight:['400','500','600','700'],
  display:"swap" })

export const metadata = {
  title: 'Portfolio website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={baloo.className}>{children}</body>
    </html>
  )
}
